services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - TURBO_TOKEN=${TURBO_TOKEN}
        - TURBO_TEAM=${TURBO_TEAM}
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:${WEB_PORT}/health || exit 1"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  database:
    image: supabase/postgres
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf 
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "dev_database"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      args:
        - TURBO_TOKEN=${TURBO_TOKEN}
        - TURBO_TEAM=${TURBO_TEAM}
    ports:
      - ${API_PORT}:${API_PORT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:${API_PORT}/health || exit 1"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      database:
        condition: service_healthy
  e2e:
    build:
      context: .
      dockerfile: ./apps/e2e/Dockerfile
    command: npx playwright test --update-snapshots --grep @snapshot
    ports:
      - 9323:9323
    environment:
      - CI='true'
      - BASE_URL=http://web:${WEB_PORT}
    depends_on:
      web:
        condition: service_healthy
      api:
        condition: service_healthy
    volumes:
      - ./apps/e2e/src/tests:/code/apps/e2e/src/tests
      - ./apps/e2e/playwright-report:/code/apps/e2e/playwright-report


# version: '3'

# # Before supabase/postgres 14.1.0
# services:
#   db:
#     image: supabase/postgres
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_PASSWORD: postgres

# # supabase/postgres 14.1.0 and beyond
# services:
#   db:
#     image: supabase/postgres
#     ports:
#       - "5432:5432"
#     command: postgres -c config_file=/etc/postgresql/postgresql.conf 
#     environment:
#       POSTGRES_PASSWORD: postgres



