services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:${WEB_PORT}/health || exit 1"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail http://localhost:${API_PORT}/health || exit 1"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  e2e:
    build:
      context: .
      dockerfile: ./apps/e2e/Dockerfile
    ports:
      - 9323:9323
    environment:
      - CI='true'
      - BASE_URL=http://web:${WEB_PORT}
    depends_on:
      web:
        condition: service_healthy
      api:
        condition: service_healthy
    volumes:
      - ./apps/e2e/src/tests:/code/apps/e2e/src/tests
      - ./apps/e2e/playwright-report:/code/apps/e2e/playwright-report


